### ISSUE TITLE
Support DiSEqC

### ISSUE THREAD

**Issue by vahid64** [mighty-p/t2scan#14]
Hi
I need to search signals with custom DiSEqC, please help me for use that.
Thanks.

**Comment by mighty-p** [comment]
Hi @vahid64 ,
I know DiSEqC only in the context of DVB-S/S2 (DVB via satellite). However, t2scan is only meant for scanning terrestrial signals (DVB-T/T2). Therefore, DiSEqC is not supported by t2scan. I am closing the issue therefore. Please re-open if I am missing anything.
