### ISSUE TITLE
Audio PID always zero in vdr format for DVB-T2 Germany

### ISSUE THREAD

**Issue by allanlatham** [mighty-p/t2scan#2]
Commands:
/usr/local/src/t2scan-master/t2scan -a 0 -s t -o mplayer > log.1
/usr/local/src/t2scan-master/t2scan -a 0 -s t -o mplayer > log.3

Result:

grep 5780 log.1 | grep SWR
SWR RP HD;ARD:578000:B8D0G19128S1T16Y0P0:T:27500:601=36:0:607:0:994:8468:17922:0
SWR RP 

grep 5780 log.3 | grep SWR
HD:578000000:INVERSION_AUTO:BANDWIDTH_8_MHZ:FEC_AUTO:FEC_NONE:QAM_AUTO:TRANSMISSION_MODE_16K:GUARD_INTERVAL_19_128:HIERARCHY_NONE:601:602+604:994

You have found the audio pids OK as you can see from the mplayer channels file but the vdr channels file contains zero. DVB-T channels are OK.

Bei der Datei fuer mplayer sind die Audio PIDs in Ordnung aber bei der fuer vdr immer null. DVB-T ist OK in beiden Faelle.

Zur Info: w_scan hat das gleiche Problem.

Temporaer Loesung: Man benutzt die Datei in vdr mit Updatechannels=4 in setup.conf. Danach kopieren und Updatechannels=0 wieder einsetzen.

Waere schoen wenn das nicht noetig waere.

Danke

**Comment by mighty-p** [comment]
Thanks for reporting, @allanlatham 
I can reproduce the issue. I did not notice it before since I let VDR update PIDs automatically. Will look into this.

**Comment by allanlatham** [comment]
Yes please. Many thanks. 

On 15 April 2018 14:23:22 CEST, mighty-p <notifications@github.com> wrote:
>Hi @allanlatham , can I resolve this ticket?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/mighty-p/t2scan/issues/2#issuecomment-381402418

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by andimik** [comment]
BTW: the initial posting seems to be not correct

`/usr/local/src/t2scan-master/t2scan -a 0 -s t -o mplayer > log.` is used for both log1 and log3

The first line should have been

`/usr/local/src/t2scan-master/t2scan -a 0 -s t > log.1`

**Comment by mighty-p** [comment]
That was probably just a copy&paste mistake by the issue opener. Please let me know if you see a problem on t2scan side here.
